import { makePropertyRepository } from '../repositories/prisma/property.repository';
import type { PrismaClient, Property } from '@rental-trust/database';

const baseProperty: Property = {
  id: 'p1',
  landlordId: 'l1',
  address: '100 King St W',
  unitNumber: '2501',
  city: 'Toronto',
  rent: 2200 as unknown as Property['rent'],
  bedrooms: 2,
  applySlug: 'slug-abc',
  status: 'ACTIVE',
  requiredDocs: ['GOVERNMENT_ID', 'PROOF_OF_INCOME'],
  createdAt: new Date(),
  updatedAt: new Date(),
};

const mockDb = {
  property: {
    findMany: jest.fn(),
    findUnique: jest.fn(),
    create: jest.fn(),
    update: jest.fn(),
  },
} as unknown as PrismaClient;

const repo = makePropertyRepository(mockDb);

beforeEach(() => jest.clearAllMocks());

describe('makePropertyRepository', () => {
  describe('findByLandlord', () => {
    it('filters by landlordId and maps _count to applicationCount', async () => {
      (mockDb.property.findMany as jest.Mock).mockResolvedValue([
        { ...baseProperty, _count: { applications: 3 } },
      ]);
      const result = await repo.findByLandlord('l1');
      expect(mockDb.property.findMany).toHaveBeenCalledWith({
        where: { landlordId: 'l1' },
        include: { _count: { select: { applications: true } } },
      });
      expect(result[0].applicationCount).toBe(3);
      expect(result[0]).not.toHaveProperty('_count');
    });
  });

  describe('findBySlug', () => {
    it('returns public shape without landlordId', async () => {
      (mockDb.property.findUnique as jest.Mock).mockResolvedValue({
        ...baseProperty,
        landlord: { name: 'Dev Landlord' },
      });
      const result = await repo.findBySlug('slug-abc');
      expect(mockDb.property.findUnique).toHaveBeenCalledWith({
        where: { applySlug: 'slug-abc' },
        include: { landlord: { select: { name: true } } },
      });
      expect(result).toMatchObject({
        address: '100 King St W',
        city: 'Toronto',
        bedrooms: 2,
        landlordName: 'Dev Landlord',
        requiredDocs: ['GOVERNMENT_ID', 'PROOF_OF_INCOME'],
      });
      expect(result).not.toHaveProperty('landlordId');
      expect(result).not.toHaveProperty('id');
    });

    it('returns null when slug not found', async () => {
      (mockDb.property.findUnique as jest.Mock).mockResolvedValue(null);
      expect(await repo.findBySlug('bad-slug')).toBeNull();
    });
  });

  describe('create', () => {
    it('does not pass applySlug in create data — generated by schema default', async () => {
      (mockDb.property.create as jest.Mock).mockResolvedValue(baseProperty);
      const data = {
        address: '100 King St W',
        city: 'Toronto',
        rent: 2200,
        bedrooms: 2,
        requiredDocs: ['GOVERNMENT_ID' as const],
      };
      await repo.create('l1', data);
      const call = (mockDb.property.create as jest.Mock).mock.calls[0][0];
      expect(call.data.landlordId).toBe('l1');
      expect(call.data).not.toHaveProperty('applySlug');
    });
  });

  describe('update', () => {
    it('updates by id', async () => {
      (mockDb.property.update as jest.Mock).mockResolvedValue(baseProperty);
      await repo.update('p1', { rent: 2500 });
      expect(mockDb.property.update).toHaveBeenCalledWith({
        where: { id: 'p1' },
        data: { rent: 2500 },
      });
    });
  });
});
