import type { PrismaClient } from '@rental-trust/database';
import type {
  IPropertyRepository,
  CreatePropertyData,
  UpdatePropertyData,
  PropertyWithCount,
  PublicProperty,
} from '../interfaces/IPropertyRepository';

export const makePropertyRepository = (db: PrismaClient): IPropertyRepository => ({
  findByLandlord: async (landlordId): Promise<PropertyWithCount[]> => {
    const rows = await db.property.findMany({
      where: { landlordId },
      include: { _count: { select: { applications: true } } },
    });
    return rows.map(({ _count, ...p }) => ({ ...p, applicationCount: _count.applications }));
  },

  findById: (id) => db.property.findUnique({ where: { id } }),

  findBySlug: async (applySlug): Promise<PublicProperty | null> => {
    const row = await db.property.findUnique({
      where: { applySlug },
      include: { landlord: { select: { name: true } } },
    });
    if (!row) return null;
    return {
      address: row.address,
      city: row.city,
      rent: Number(row.rent),
      bedrooms: row.bedrooms,
      landlordName: row.landlord.name,
      requiredDocs: row.requiredDocs,
    };
  },

  create: (landlordId, data: CreatePropertyData) =>
    db.property.create({
      data: {
        landlordId,
        address: data.address,
        unitNumber: data.unitNumber,
        city: data.city,
        rent: data.rent,
        bedrooms: data.bedrooms,
        requiredDocs: data.requiredDocs,
        // applySlug is generated by @default(cuid()) in schema — never from client input
      },
    }),

  update: (id, data: UpdatePropertyData) => db.property.update({ where: { id }, data }),
});
